### ISSUE TITLE
Registering the package and package name

### ISSUE THREAD

**Issue by meggart** [meggart/Zarr.jl#13]
Hi @visr 

I would like to move forward and make a first release of the package as it is right now. I have added a lot of unit tests and tried to improve on the documentation. Unfortunately the S3 tests are still broken until AWSCore tags a new release, but since the object store is not yet documented anyway that should not be a problem. 

The main reason that I want to register is that I need this as a dependency for another unregistered package.  Would you have any objection against this? 

I think there were two issues we did not solve when we started: package name and where it is hosted. Do you think we should move this to JuliaGeo or somewhere else before registering () the format is actually not Geo-specific) and should we rename the package to Zarr.jl instead of ZarrNative?

**Comment by visr** [comment]
Hi Fabian, great to see all the progress you've made, and sorry I haven't been of much help.

I think it's good to register it. Since the new registry is based on UUID's, renaming the package afterward should be less painful than it was before. And moving it can of course be done at any point.

Indeed JuliaGeo may not seem the most logical place. For me it's fine to keep it here. Other options that might make sense are zarr-developers, JuliaIO, or perhaps JuliaData.

I just checked if there was already concrete effort for a C implementation, but there doesn't seem to be. I see there is discussion about naming here: https://github.com/zarr-developers/zarr/issues/407#issuecomment-464723018

To me, especially seeing how far this is and how far the C implementation is, and considering that native julia will in most cases be desirable over a C wrapper (as long as it is implented correctly), I'd still say to rename ZarrNative.jl to Zarr.jl. A C wrapper could be named ZarrC.jl for instance. (And a Rust wrapper ZarrRust.jl, ZarrGo etc.). But I don't feel too strongly about this, so go with what you prefer.
