### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by eloop** [meggart/Zarr.jl#61]
I've been playing around with Zarr a bit and it would seem that there is some very large differences between a native array and a Zarr. Just wondering if there is something I'm missing here? eg 

```
using Zarr

function test()
    d = (10,10,10)
    c = (100,100,100)

    z2 = zeros(Float32, d)
    @show typeof(z2), size(z2)
    @time for i in CartesianIndices(z2)
        z2[i] = i[1]+i[2]+i[3]
    end
    @time for i in CartesianIndices(z2)
        z2[i] = i[1]+i[2]+i[3]
    end

    z1 = zzeros(Float32, d...,
                compressor=Zarr.NoCompressor(),
                chunks=c)
    @show z1
    @time for i in CartesianIndices(z1)
        z1[i] = i[1]+i[2]+i[3]
    end
    @time for i in CartesianIndices(z1)
        z1[i] = i[1]+i[2]+i[3]
    end

end

test()

```

> (typeof(z2), size(z2)) = (Array{Float32, 3}, (10, 10, 10))
>   0.000005 seconds
>   0.000005 seconds
> z1 = ZArray{Float32} of size 10 x 10 x 10
>   9.879543 seconds (67.00 k allocations: 7.453 GiB, 0.35% gc time)
>   9.857349 seconds (67.00 k allocations: 7.453 GiB, 0.13% gc time)
>

**Comment by meggart** [comment]
First thing that pops up is that you are using chunks of size 100x100x100 for storing an array of size 10x10x10 so you over-allocate a lot and generate overhead when reading and writing. 

Second, Zarr is slow in random-access of data. Typically its use-case is for storing data on disk or Object store, so you assume that chunks of data are read and written at a time and some access overhead is okay since it is negligible compared to data transfer time. So in any case you should try to avoid access of single elements and rather try write write blocks of data. In your example, if you use `broadcast!` instead of the loop, it will iterate over each chunk of your array and store the results , so instead of 

````julia
@time for i in CartesianIndices(z1)
    z1[i] = i[1]+i[2]+i[3]
end
````

you should do 

````julia
@time broadcast!(z1, CartesianIndices(z1)) do i
    i[1]+i[2]+i[3]
end
````
which is faster than your original version, but will of course never match performance of Julia's native arrays.

**Comment by eloop** [comment]
It hadn't occurred to me that the entire chunk of data would be allocated even when the array was smaller. I'd changed the array size down to 10 from 100 to make the test run to completion for the example. If you match the array size and chunk size such so that the zarr array is one single chunk I'm still a bit surprised at the vast difference between the native array and the in memory no compression zarr. E.g. trying d=(100,100,100) and c=(100,100,100) in the example has the native array taking ~0.003s and the zarr not completing within the mintutes I waited. My interest in Zarr besides a storage format was to see if it's a practical, cache friendly, in memory format for working with arrays in the hundreds of GBs. It would seem that the best way to proceed will be to read chunks off disk manually into native arrays for the computationally intensive operations. Thanks for the broadcast! tip, it's ~4-5 times slower than the native array compared to many orders of magnitude for the naive loop.
